### ISSUE TITLE
R_CMethodDef Declaration

### ISSUE THREAD

**Issue by wrathematics** [bastistician/polyCub#1]
In src/init.c, you don't specify the fourth field of your `R_CMethodDef` declaration. If you compile with `-Wmissing-field-initializers` in gcc, you will see the warning:

```
init.c:18:5: warning: missing initializer for field ‘types’ of ‘R_CMethodDef {aka const struct <anonymous>}’ [-Wmissing-field-initializers]
     {"C_polygauss", (DL_FUNC) &C_polygauss, 13},
     ^
In file included from init.c:12:0:
/usr/share/R/include/R_ext/Rdynload.h:55:31: note: ‘types’ declared here
     R_NativePrimitiveArgType *types;
                               ^~~~~
init.c:19:5: warning: missing initializer for field ‘types’ of ‘R_CMethodDef {aka const struct <anonymous>}’ [-Wmissing-field-initializers]
     {NULL, NULL, 0}
     ^
In file included from init.c:12:0:
/usr/share/R/include/R_ext/Rdynload.h:55:31: note: ‘types’ declared here
     R_NativePrimitiveArgType *types;
                               ^~~~~
```

You can see what it's complaining about here https://cran.r-project.org/doc/manuals/R-exts.html#Registering-native-routines (see their `myC_t` bit). It's probably not dangerous, but it's also easy enough to fix. Just change your `CEntries` line to this:

```c
static const R_CMethodDef CEntries[] = {
    {"C_polygauss", (DL_FUNC) &C_polygauss, 13, NULL},
    {NULL, NULL, 0, NULL}
};
```

It's probably not dangerous though, so feel free to close the issue if you prefer.

**Comment by bastistician** [comment]
Thanks for testing! I will add the `types` declaration.

I had based my init file on
```r
tools::package_native_routine_registration_skeleton(".", character_only = FALSE)
```
which simply omits the `types` argument (as do most base R packages).

[Searching for R_NativePrimitiveArgType on GitHub](https://github.com/search?q=org%3Acran+R_NativePrimitiveArgType&type=Code) I *did* find some R packages which use proper code, for example, [**cluster**](https://github.com/cran/cluster/blob/master/src/init.c), [**potts**](https://github.com/cran/potts/blob/master/src/init.c), [**cheddar**](https://github.com/cran/cheddar/blob/master/src/cheddar.cpp), [**earth**](https://github.com/cran/earth/blob/master/src/rentries.c). **polyCub** will be among these soon.
