### ISSUE TITLE
rgeos archived

### ISSUE THREAD

**Issue by rsbivand** [bastistician/polyCub#4]
@bastistician rgeos was archived two days ago, so please do move to submit an updated version of polyCub as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details. Maybe consider the geos package as a replacement (unchecked).

**Comment by bastistician** [comment]
Thank you, Roger, I know and am already prepared to remove remaining references to **rgeos** in the next release. I had used it as an alternative provider of the `"gpc.poly"` class, given the [license trouble with **gpclib**](https://github.com/rdpeng/gpclib/issues/1). Now that both packages are inactive on CRAN, I'll probably drop the `"gpc.poly"` interface.

**Comment by rsbivand** [comment]
You are welcome to use the rgeos code for those classes if that would help. It depends on the operators or predicates you need; polyclip is another alternative to the geos package and closer to gpclib, I think.
